---

# ClusterBlueprintType defines a valid output/input between
# Components
# +optional
apiVersion: carto.run/v2alpha1

# Description describes this output to provide documentation to
# consumers.
# +optional
description: <string>
kind: ClusterBlueprintType
metadata: {}

# Qualifier is provided to avoid name collisions when blueprint
# authors start creating new types on a platform. There is a
# validation rule that metadata.name must be of the form:
# <qualifier>.<name> or <qualifier>-<name>. If the qualifier is
# omitted, then just <name> will suffice. Note: For TAP, this
# should be "tap" to avoid collisions with blueprint authors. We
# recommend other platforms follow this pattern also.
# +optional
qualifier: <string>

# Schema a JSON schema that is a valid representation of a type.
# Due to a limitation in k8s CRD definitions, this field accepts
# any valid JSON, however the validation will fail if it's not
# JSONSchema as per apiextensions.JSONSchemaProps (see:
# https://pkg.go.dev/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions@v0.24.2#JSONSchemaProps)
# Todo: explain the problem with the absence of schema here, and
# semantic error checking
schema: <any>
